# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'iOS Example' do

  use_frameworks!

  pod 'SnapKit', '~> 4.0.0'
  pod 'AnyFormatKit', :path => '../../'

end
